apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: default
type: Opaque
stringData:
  # DB credentials (IPv4 Connection Pooler settings)
  PGHOST: aws-1-eu-west-1.pooler.supabase.com
  PGPORT: "5432"
  PGUSER: postgres.tjrwpdwwousjvrrackat
  PGDATABASE: postgres
  PGPASSWORD: "-hHgNt6Wwn8&ti_"
