apiVersion: v1
kind: Service
metadata:
  name: trackflow-web-service
  namespace: default
  labels:
    app: trackflow-web
  annotations:
    # Provisions an AWS Network Load Balancer (NLB) which is faster and modern
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: trackflow-web
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
