// Precompiles views/*.html into build/views.js for the Cloudflare Worker.
// Workers block runtime code generation (eval / new Function), which nunjucks
// uses to compile templates on the fly, so templates are compiled ahead of time.
const fs = require('fs');
const path = require('path');
const nunjucks = require('nunjucks');

const viewsDir = path.join(__dirname, '..', 'views');
const outDir = path.join(__dirname, '..', 'build');

const compiled = nunjucks.precompile(viewsDir, {
  include: [/\.html$/],
  wrapper(templates) {
    const entries = templates.map(({ name, template }) => `  ${JSON.stringify(name)}: (function () {\n${template}\n})()`);
    return `// Generated by scripts/build-views.js. Do not edit.\nmodule.exports = {\n${entries.join(',\n')}\n};\n`;
  }
});

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'views.js'), compiled);
console.log('Precompiled views to build/views.js');
